### PR TITLE
working spades logic

### PR DESCRIPTION
**Pull request by davidbrowning**
This is not very clean, but here it is.

### CODE REVIEW

**Comment by mikamerath** [comment]
You're going to need to heavily change the way this is organized.
1. Create a subdirectory called SpadesLogic. Add this subdirectory to the CMakeList.txt under the source folder.
2. Create a CMakeList.txt in your SpadesLogic directory and add your files to a library so we can access them in a game. (To do this, look at the CMakeList.txt in the playerAPI directory, it will point you in the correct place).
3. CMake your project and be sure it actually Builds.
4. Write Unit tests that be sure we can actually verify that the code you have written works. (This can be done in a separate pull)

Do all of these things, commit the changes, and then we can start the code review process.

**Comment by mikamerath** [comment]
Also, please run clang format on your code, it's in the coding standard

**Comment by katiesweet** [comment]
Thanks for posting this @davidbrowning. It was good to see it working in class today! It looks like you have copied a lot of the code over from the API directory into your files to get it work locally. If you could #include those instead, just so their isn't any redundancy, that would be awesome!

**Comment by davidbrowning** [comment]
The only issue is that they're not copies of them. I'm doing everything I
can to get it to work with what is actually there.

**Comment by katiesweet** [comment]
Okay! If the current API doesn't work for you, let me know so I can make changes. Better, if you know what the changes need to be, and they won't cause problems with other people's logic (i.e. they are additions to the API and not modifications of existing functions), go ahead and add them directly yourself.

**Comment by davidbrowning** [comment]
You guys have done a great job, I just wanted to get it working and took
some shortcuts. I really like how it looks now, and I'm almost there on
plugging spades into it.

On Nov 3, 2016 3:29 PM, "katiesweet" notifications@github.com wrote:

Okay! If the current API doesn't work for you, let me know so I can make
changes. Better, if you know what the changes need to be, and they won't
cause problems with other people's logic (i.e. they are additions to the
API and not modifications of existing functions), go ahead and add them
directly yourself.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/michaelkamerath/SharedServer/pull/21#issuecomment-258279812,
or mute the thread

**Comment by davidbrowning** [comment]
For some reason my commits weren't showing up here.

**Pull request closed without merging**
