### PR TITLE
InitializeSpades test is failing

### PR DESCRIPTION
**Pull request by davidbrowning**
@C-Merrill @katiesweet I tweaked spades a bit trying to figure out why the initializeSpades test is failing (borrowing from crazy eights). I wrote the init test and I'm having trouble figuring out why it is failing. Can I get a hand?

### CODE REVIEW

**Comment by davidbrowning** [comment]
**It has something to do with how I'm initializing spades.**

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "setlocal
"C:\Program Files\CMake\bin\ctest.exe" --force-new-ctest-process -C Debug
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 8.	RUN_TESTS	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133

**Comment by davidbrowning** [comment]
@gitCameron Did you have anything similar with initializeCrazyEights?

**Review by C-Merrill — APPROVED** [review]
Builds and tests pass for me

**Comment by davidbrowning** [comment]
@C-Merrill sorry!!! I had just finished the validMove test when I saw your approval!

**Comment by C-Merrill** [comment]
@davidbrowning no problem. Everything builds and passes still but I'm getting this. Is it a problem?
capture

**Comment by davidbrowning** [comment]
Yeah, it isn't an issue, I think that is just legacy stuff I need to clean up

**Pull request merged**
