### PR TITLE
Added Passing to Player

### PR DESCRIPTION
**Pull request by trevorjewkes**
I think this will work to handle passing.

@katiesweet Does this look like what we were talking about last night? Or that it will at least work?

### CODE REVIEW

**Comment by katiesweet** [comment]
@trevorjewkes @michaelkamerath @C-Merrill this builds, so I think we are good to go. Once we get the message for serializing and deserializing a vector of cards, I'll come through and update this.

**Review by C-Merrill — APPROVED** [review]
Looks good to me

**Comment by katiesweet** [comment]
@C-Merrill @michaelkamerath Can we get this and the AI merged, or are we waiting on the two other pull requests? I think those ones might still be a little while.

**Comment by C-Merrill** [comment]
I'm good for merging it, but I don't think @michaelkamerath has looked at it yet.

**Comment by mikamerath** [comment]
@katiesweet @C-Merrill, I'll resolve the conflicts and merge this in

**Comment by mikamerath** [comment]
@trevorjewkes, good job with this

**Pull request merged**
