### PR TITLE
Player API unit tests, bug fix

### PR DESCRIPTION
**Pull request by katiesweet**
@frangello added some unit tests for the PlayerAPI, added a setBid function, and fixed the insertCardToHand function (it wasn't sorting properly). 

@michaelkamerath, are you okay with these changes? I'm not sure we need a whole code review on this one, unless you think it's worth while.

This should close issue #22

### CODE REVIEW

**Comment by mikamerath** [comment]
@katiesweet I think we should do a code review for this since there is a bug fix. Fortunately, nothing else is depending on this so we won't have to worry about much.

**Comment by katiesweet** [comment]
Okay!
@trevorjewkes @Shemarama @davidbrowning will you guys please review this?

**Comment by mikamerath** [comment]
@trevorjewkes @Shemarama @davidbrowning You guys only need to review the changes in Player as the unit tests don't affect you.

**Review by trevorjewkes — APPROVED** [review]

**Review by Shemarama — APPROVED** [review]

**Review by mikamerath — APPROVED** [review]

**Comment by mikamerath** [comment]
Thanks for doing this

**Pull request merged**
