### PR TITLE
Persistent storage and log in functionality

### PR DESCRIPTION
**Pull request by dakotalraymond**

### CODE REVIEW

**Comment by mikamerath** [comment]
@dakotalraymond, can you provide some unit tests to ensure that this works?

**Comment by dakotalraymond** [comment]
@dustinos3, can you write these unit tests so I can keep working on the GUI?

**Comment by dakotalraymond** [comment]
@dustinos3 nevermind, I got it. @michaelkamerath We should be good now.

**Comment by katiesweet** [comment]
@dakotalraymond good job on this! I'm excited for these changes. This builds, and I tested it a bit with my client and it seems to connect, read the message, and send a response how I'd expect. However, your test case fails... 

screen shot 2016-11-30 at 9 55 51 pm

**Review by C-Merrill — APPROVED** [review]
Builds and passes tests.

**Comment by katiesweet** [comment]
@C-Merrill The tests don't pass for me... Is this a problem?

**Comment by C-Merrill** [comment]
Yeah I just saw that. I'm trying to figure out what the deal is there.

**Comment by dakotalraymond** [comment]
@katiesweet Does that last push help? The original passes on mine, so I'm just guessing.

**Comment by katiesweet** [comment]
@dakotalraymond You fixed one of them! Now it only complains about one bad file descriptor.

**Comment by dakotalraymond** [comment]
Ok @katiesweet I'm hoping that should work. I think it was mad because when the login function was called, it was trying to write to a connection that wasn't there.

**Comment by katiesweet** [comment]
@dakotalraymond Says no errors detected, but it still looks like it is yelling about a bad file descriptor.

screen shot 2016-11-30 at 10 54 28 pm

**Comment by C-Merrill** [comment]
I vote we don't worry about it for now. I would say you should move writeToDatabase to be called in a destructor rather than every time someone registers, but that can be done later. @michaelkamerath can we pull this in?

**Comment by mikamerath** [comment]
@C-Merrill, @katiesweet, @dakotalraymond, I'm pretty leery about letting this in as it seems to be having a problem with the socket descriptor for Linux. However, that seems like something @droidkfx would know more about. We'll merge this in, and then bring it up in class today.

**Comment by mikamerath** [comment]
@dakotalraymond, also, please don't use raw pointers in the future. You initialized one in your unit test and then never deleted it. Instead use std::unique_ptr or std::shared_ptr to manage memory for you.

**Pull request merged**
