### PR TITLE
Adding Lobby Functionality to Start Game with AIs

### PR DESCRIPTION
**Pull request by katiesweet**
Start of a few little changes needed to get this project working.

### CODE REVIEW

**Comment by katiesweet** [comment]
PS, there are quite a few issues with this at the moment. It's more for reference than anything.

**Comment by C-Merrill** [comment]
@katiesweet keep up the work on this. I think we'll wait til it's a bit more stable to pull it in.

**Comment by katiesweet** [comment]
@C-Merrill Sorry I haven't gotten this up sooner. I made a huge mistake and went down a rabbit hole extracting HumanPlayer from Player. Just turned into too big of a mess, so I'm scratching that (it builds, but I get some runtime error that I can't figure out. If you want to go down that route, I can push my work for reference.) I wouldn't count on too many good changes here tonight... I'll do my best, but like I said this morning, no promises on this thing...

**Comment by C-Merrill** [comment]
@katiesweet no problem. Do what you can. There are changes here that are really important if you can get them going. Can we get to a point where it is safe to merge?

**Comment by katiesweet** [comment]
@C-Merrill I'm about 10 minutes from pushing up a good version. I'm going to close this pull request then and open a new one (it'll be from a different branch).

Just to keep you posted on what's going on:

I'm not done with the functionality I need to get it 100% working, but you should at least be able to create a new game of Crazy Eights, filling it in with AI's by that point, and the START GAME functionality will be the same for all games.

Afterwards, I am going to add a confirmation for all players to confirm that they know the game is starting (so our client doesn't miss any messages) and will start the game.

Something that really needs to be done (once I push) is getting the UpdateGameStateMessage function to gather the information it needs. Also, the other logics (I will do 8's) needs to be updated to match this format.

**Comment by C-Merrill** [comment]
@katiesweet That sounds like a good idea. I'll start looking at UpdateGameStateMessage. I probably won't make much progress in the next 90 minutes, but I'll see what I can do.

**Pull request closed without merging**
