### PR TITLE
Split into hpp and cpp files

### PR DESCRIPTION
**Pull request by davidbrowning**
should fix issue #33

### CODE REVIEW

**Comment by mikamerath** [comment]
Please fix your merge conflicts and make sure everything is correct.

**Comment by davidbrowning** [comment]
I need to run it through clang-format, but I think I fixed the merge issues.

**Comment by mikamerath** [comment]
This doesn't build, you need to remove all of the things that have >>>>>/refs or >>>>>HEAD and make sure that all of the code is correct

**Comment by C-Merrill** [comment]
We may need a workshop on resolving merge conflicts...

**Comment by davidbrowning** [comment]
That would be excellent

**Comment by mikamerath** [comment]
@davidbrowning, Merge conflicts happen when you modify the same line of code as somebody else. In both of the files listed, find where the code conflicts and choose which one you'll want. It'll either be >>>>>>>>HEAD or >>>>>>>your Local branch. Sometimes you'll want both of the changes

**Comment by C-Merrill** [comment]
@davidbrowning, you need to merge michaelkamerath/master into your local branch, look through the files that say they have merge conflicts, and resolve them as Michael mentioned.

**Review by C-Merrill — APPROVED** [review]
Worked with David to get this working. SpadesLogic now builds, although networking doesn't and there is a redefinition of Card::Serialize that doesn't allow a couple others to build. Long story short, this PR looks good to merge and we can fix these errors later that are not related to SpadesLogic.

**Comment by mikamerath** [comment]
This pull request is looking a little suspicious, did you run a git fetch before doing git pull to merge? There are changes listed here that are already a part of master

**Comment by C-Merrill** [comment]
@michaelkamerath we good on this?

**Pull request merged**
