### PR TITLE
Initial commit for spades docs

### PR DESCRIPTION
**Pull request by davidbrowning**
Let us know if you standardize the .tex format and/or write up a template for how it's supposed to look.

### CODE REVIEW

**Comment by C-Merrill** [comment]
Each document will have a directory. Inside the directory, there will be a main <filename>.tex file, a sections folder, a graphics folder, and any other folder as necessary. Therefore, the commit should consist of a .tex file added to the sections directory, any graphics added to graphics directory, and necessary changes to the main <filename>.tex file. Those changes include \include{sections/<sectionname> inside the document and any necessary packages included in the preamble. I'll add a graphics path pointing to the graphics directory, so include graphics based on that relative path.

**Comment by davidbrowning** [comment]
Sweet! I think I fixed it. Is there anywhere you'd like a pdf for reference or just the straight up tex and such?

**Comment by C-Merrill** [comment]
Just the .tex files and graphics. Please do not include the pdf in your commit. I don't think master has it ignored yet, so just please make sure not to include it in your commit for now.

**Comment by davidbrowning** [comment]
got it!

**Review by C-Merrill — CHANGES_REQUESTED** [review]
Review the standard and adjust to it. Your .tex file shouldn't have a preamble.

**Comment by davidbrowning** [comment]
Is this closer to what it should look like?

**Comment by C-Merrill** [comment]
No, your Spades Logic needs to be one section of the shared SDD, not a separate document. It needs to be compiled into one document with everyone else's SDD contribution. See the Policy merge commit. Yours should look like that.

**Comment by C-Merrill** [comment]
Please open a new commit when the necessary changes have been applied

**Pull request closed without merging**
