### PR TITLE
Added Networking Functionality to Crazy Eights and Player

### PR DESCRIPTION
**Pull request by Shemarama**
@michaelkamerath @katiesweet @davidbrowning @gitCameron

@katiesweet Did you mean to get rid of getPlayerId() in player.cpp?  Just wondering

### CODE REVIEW

**Comment by katiesweet** [comment]
No, I did not mean to do that. Sorry! Thanks for adding this stuff, @gitCameron and @Shemarama!

**Comment by C-Merrill** [comment]
@Shemarama We'll need you to merge again and resolve conflicts. Please do that ASAP.

**Comment by Shemarama** [comment]
@C-Merrill Okay, I fixed the merge conflicts.

**Review by C-Merrill — APPROVED** [review]
Builds. @Shemarama, get unit tests ASAP please

**Pull request merged**
